
-- Ctrl e to escapse
hs.hotkey.bind({"ctrl"}, "e", function()
    hs.eventtap.keyStroke({}, "ESCAPE")
end)

-- Arrow keys
hs.hotkey.bind({"option"}, "j", function()
    hs.eventtap.keyStroke({}, "left")
end)
hs.hotkey.bind({"option"}, "i", function()
    hs.eventtap.keyStroke({}, "up")
end)
hs.hotkey.bind({"option"}, "k", function()
    hs.eventtap.keyStroke({}, "down")
end)
hs.hotkey.bind({"option"}, "l", function()
    hs.eventtap.keyStroke({}, "right")
end)

-- command space to return
hs.hotkey.bind({"command"}, "space", function()
    hs.eventtap.keyStroke({}, "return")
end)

-- Number keys

hs.hotkey.bind({"shift","ctrl","option","command"}, "a", function()
    hs.eventtap.keyStroke({}, "1")
end)
hs.hotkey.bind({"shift","ctrl","option","command"}, "s", function()
    hs.eventtap.keyStroke({}, "2")
end)
hs.hotkey.bind({"shift","ctrl","option","command"}, "d", function()
    hs.eventtap.keyStroke({}, "3")
end)
hs.hotkey.bind({"shift","ctrl","option","command"}, "f", function()
    hs.eventtap.keyStroke({}, "4")
end)
hs.hotkey.bind({"shift","ctrl","option","command"}, "g", function()
    hs.eventtap.keyStroke({}, "5")
end)
hs.hotkey.bind({"shift","ctrl","option","command"}, "h", function()
    hs.eventtap.keyStroke({}, "6")
end)
hs.hotkey.bind({"shift","ctrl","option","command"}, "j", function()
    hs.eventtap.keyStroke({}, "7")
end)
hs.hotkey.bind({"shift","ctrl","option","command"}, "k", function()
    hs.eventtap.keyStroke({}, "8")
end)
hs.hotkey.bind({"shift","ctrl","option","command"}, "l", function()
    hs.eventtap.keyStroke({}, "9")
end)
hs.hotkey.bind({"shift","ctrl","option","command"}, ";", function()
    hs.eventtap.keyStroke({}, "0")
end)

-- Special characters - command right

hs.hotkey.bind({"option"}, "h", function()
    hs.eventtap.keyStroke({"shift"}, "1")
end)
hs.hotkey.bind({"option"}, "u", function()
    hs.eventtap.keyStroke({"shift"}, "2")
end)
hs.hotkey.bind({"option"}, "o", function()
    hs.eventtap.keyStroke({"shift"}, "3")
end)
hs.hotkey.bind({"option"}, "y", function()
    hs.eventtap.keyStroke({"shift"}, "4")
end)
hs.hotkey.bind({"option"}, ";", function()
    hs.eventtap.keyStroke({"shift"}, "5")
end)
hs.hotkey.bind({"option"}, "m", function()
    hs.eventtap.keyStroke({"shift"}, "6")
end)
hs.hotkey.bind({"option"}, "n", function()
    hs.eventtap.keyStroke({"shift"}, "7")
end)
hs.hotkey.bind({"option"}, "'", function()
    hs.eventtap.keyStroke({"shift"}, "8")
end)
hs.hotkey.bind({"command"}, "j", function()
    hs.eventtap.keyStroke({"shift"}, "9")
end)
hs.hotkey.bind({"command"}, "k", function()
    hs.eventtap.keyStroke({"shift"}, "0")
end)

-- Special characters - command left


hs.hotkey.bind({"command"}, "l", function()
    hs.eventtap.keyStroke({"shift"}, "-")
end)
hs.hotkey.bind({"command"}, ";", function()
    hs.eventtap.keyStroke({}, "=")
end)
hs.hotkey.bind({"command"}, "'", function()
    hs.eventtap.keyStroke({}, "-")
end)
hs.hotkey.bind({"command"}, "\\", function()
    hs.eventtap.keyStroke({"shift"}, "=")
end)


